indent_style = "Visual"
fn_single_line = true
imports_layout = "Vertical"
merge_imports = true
max_width = 80
match_block_trailing_comma = true
reorder_impl_items = true
struct_field_align_threshold = 20
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
